[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink/contracts-ccip/=lib/chainlink-local/lib/ccip/contracts/",
    "@chainlink/contracts/=lib/chainlink-local/lib/chainlink-brownie-contracts/contracts/",
    "@chainlink/local/src/=lib/chainlink-local/src/",
    "@chainlink/local/=lib/chainlink-local/",
    "ccip/=lib/chainlink-local/lib/ccip/contracts/",
    "chainlink-brownie-contracts/=lib/chainlink-local/lib/chainlink-brownie-contracts/contracts/src/v0.6/vendor/@arbitrum/nitro-contracts/src/",
    "chainlink-local/=lib/chainlink-local/src/",
    "ds-test/=lib/chainlink-local/lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/chainlink-local/lib/forge-std/src/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
